### ISSUE TITLE
Assess modchip compatibility status

### ISSUE THREAD

**Issue by 9ary** [redolution/iplboot#10]
- [x] PicoBoot should be actively supported. See https://github.com/webhdx/PicoBoot/issues/22 for our relationship with them.
- [x] Qoob Pro and ViperGC Extreme should still be supported, as they have plenty of flash. Testing is needed.
- [ ] ViperGC should still fit as well. Testing is needed in case it requires compression, but otherwise it works completely identically to VGCE.
- [x] Qoob SX is the trickiest because it's hard to make things fit on it. Support may be put on hold.
- [x] Xeno (xenopie) support should be yote. I don't think anyone was ever able to test it properly and it's now completely obsolete. It was also specific to my Raspberry Pi-based Xeno clone which was absolutely awful, because no AVR has enough memory to hold iplboot. (fixed in #9)
- [ ] boot.gci support (for game exploits) should be maintained as well. (#27)
